spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/sport-result
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiffndla0423
  jpa:
    hibernate:
      ddl-auto: none
